### ISSUE TITLE
Remove secret values and change from .env

### ISSUE THREAD

**Issue by crushingCodes** [Keshav2136/online-retail-marketplace#4]
https://github.com/Keshav2136/online-retail-marketplace/blob/a0443f9c2aee285bd1ffbfa03863facfe6119e46/onlineretail/.env#L1

I was going to look at your code to see if you were locked into Django and I noticed you are saving sensitive info into github.

Here is a link with more info,
https://dev.to/somedood/please-dont-commit-env-3o9h
but long story short you need to:

1. regenerate your secret
2. add .env to your .gitignore
3. save empty vars to .env-default(commit this to git)
4. remove .env from being tracked
5. push to github and ensure .env doesnt exist
4. use .env-config to make .env and complete the variables with correct answers

Following these steps will help keep your webapp secure

**Comment by Keshav2136** [comment]
I'll get it in the next commit. Btw I've moved to Firebase

**Comment by Keshav2136** [comment]
This has been fixed. Thanks
